version: '3.4'

services:
  productdb:
    container_name: productdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  dockertestapi:
    container_name: dockertestapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProductConnectionString=Server=productdb;Database=DockerProductDb;User Id=sa;Password=SwN12345678;"
    ports:
      - "11002:80"
    depends_on: 
      - productdb

  dockertestapp:
    container_name: dockertestapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:ProductAddress=http://dockertestapi/api/"
    ports:
      - "11001:80"
    depends_on:
      - dockertestapi

  

